{{- if .Values.tts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tts.service.name }}
  namespace: {{ include "pattern-tts.namespace" . }}
  labels:
    {{- include "pattern-tts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tts.service.type }}
  ports:
    - port: {{ .Values.tts.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pattern-tts.selectorLabels" . | nindent 4 }}
{{- end }}
